// data.js — catalog & content

window.APP_DATA = {
  collections: [
    { id: "bombes", name: "Bombes de bain", count: 24, swatch: "pink",
      tagline: "Bouillonnement effervescent",
      description: "Des sphères qui tourbillonnent, fondent et parfument votre eau d'huiles essentielles précieuses." },
    { id: "sels", name: "Sels & infusions", count: 18, swatch: "lilac",
      tagline: "Minéraux purs de l'Himalaya",
      description: "Cristaux roses, gris, noirs — récoltés à la main, infusés de fleurs séchées." },
    { id: "savons", name: "Savons artisanaux", count: 31, swatch: "vanilla",
      tagline: "Saponifiés à froid en Provence",
      description: "Pains de savon découpés, surgras, riches en beurres végétaux d'origine contrôlée." },
    { id: "cremes", name: "Crèmes & laits corps", count: 22, swatch: "mint",
      tagline: "Caresses végétales",
      description: "Émulsions onctueuses, beurres fouettés, laits soyeux pour une peau confortable." },
    { id: "huiles", name: "Huiles précieuses", count: 14, swatch: "pink",
      tagline: "Or liquide à fleur de peau",
      description: "Macérats huileux et huiles vierges premières, pressées à froid." },
    { id: "coffrets", name: "Coffrets cadeaux", count: 9, swatch: "lilac",
      tagline: "L'art d'offrir le bain",
      description: "Sélections sur-mesure, emballées à la main dans nos ateliers." },
  ],

  bestsellers: [
    { id: "p1", name: "Nuage Rose", subtitle: "Bombe de bain à la rose de Damas", price: "12€",
      collection: "bombes", tag: "Best-seller", swatch: "pink", rating: 4.9, reviews: 1284,
      ingredients: "Bicarbonate de sodium, acide citrique, beurre de karité, huile essentielle de rose, pétales séchés." },
    { id: "p2", name: "Sel d'Hokkaido", subtitle: "Sel minéral & yuzu confit", price: "24€",
      collection: "sels", tag: "Nouveauté", swatch: "vanilla", rating: 4.8, reviews: 412,
      ingredients: "Sel marin du Japon, huile de yuzu, fleur de cerisier, magnésium." },
    { id: "p3", name: "Lait de Lune", subtitle: "Crème corporelle nourrissante", price: "32€",
      collection: "cremes", tag: "Bio", swatch: "mint", rating: 4.9, reviews: 876,
      ingredients: "Beurre de karité bio, huile d'amande douce, eau florale de fleur d'oranger." },
    { id: "p4", name: "Vanille Givrée", subtitle: "Savon surgras au monoï", price: "14€",
      collection: "savons", tag: "Vegan", swatch: "vanilla", rating: 4.7, reviews: 623,
      ingredients: "Huile de coco saponifiée, monoï de Tahiti, gousses de vanille bourbon." },
    { id: "p5", name: "Bain de Lavande", subtitle: "Huile parfumée des Alpilles", price: "38€",
      collection: "huiles", tag: "Origine controlée", swatch: "lilac", rating: 4.9, reviews: 298,
      ingredients: "Huile de jojoba, lavande fine AOP, immortelle, romarin." },
    { id: "p6", name: "Macaron Pistache", subtitle: "Bombe moussante gourmande", price: "11€",
      collection: "bombes", tag: "Édition limitée", swatch: "mint", rating: 4.8, reviews: 541,
      ingredients: "Bicarbonate, acide citrique, lait d'amande, pistache de Bronte, fleur d'oranger." },
    { id: "p7", name: "Pétales d'Aube", subtitle: "Sel infusé hibiscus & rose", price: "26€",
      collection: "sels", tag: "Best-seller", swatch: "pink", rating: 4.8, reviews: 367,
      ingredients: "Sel d'Himalaya, hibiscus, pétales de rose, huile de pépins de raisin." },
    { id: "p8", name: "Coton Câlin", subtitle: "Lait de bain cocooning", price: "28€",
      collection: "cremes", tag: "Bio", swatch: "lilac", rating: 4.9, reviews: 921,
      ingredients: "Lait d'avoine, beurre de cacao, fleur de coton, vitamine E." },
  ],

  bundles: [
    { id: "b1", name: "Le Rituel du Dimanche", price: "78€", was: "94€",
      includes: ["Nuage Rose", "Sel d'Hokkaido", "Lait de Lune"],
      tag: "Coffret signature", swatch: "pink",
      story: "Trois temps pour s'offrir une parenthèse : effervescence, infusion, hydratation." },
    { id: "b2", name: "Escapade Provence", price: "92€", was: "112€",
      includes: ["Bain de Lavande", "Vanille Givrée", "Pétales d'Aube"],
      tag: "Made in France", swatch: "lilac",
      story: "Un voyage olfactif entre les champs de lavande et les marchés provençaux." },
    { id: "b3", name: "Découverte Mini", price: "42€", was: "54€",
      includes: ["6 bombes mini", "Pochon en lin"],
      tag: "Idée cadeau", swatch: "mint",
      story: "Six fragrances en miniature, parfaites pour explorer notre univers." },
  ],

  benefits: [
    { icon: "🌿", label: "Bio & vegan certifié", sub: "Cosmos Organic" },
    { icon: "🇫🇷", label: "Fabriqué en France", sub: "Ateliers de Grasse" },
    { icon: "🌸", label: "Origine contrôlée", sub: "Filière transparente" },
    { icon: "📦", label: "Livraison offerte", sub: "Dès 60€ d'achat" },
    { icon: "♻️", label: "Emballages compostables", sub: "Zéro plastique" },
  ],

  testimonials: [
    { name: "Camille L.", city: "Paris 11ᵉ", text: "Le Nuage Rose a transformé mon dimanche soir en rituel sacré. Mon mari a fini par m'en commander aussi.", product: "Nuage Rose", rating: 5 },
    { name: "Sophie M.", city: "Lyon", text: "Enfin une marque qui ne ment pas sur la composition. Je lis tous les ingrédients et tout est nickel.", product: "Lait de Lune", rating: 5 },
    { name: "Anaïs D.", city: "Bordeaux", text: "L'odeur de la bombe Macaron Pistache… c'est dangereux d'avoir envie de la croquer.", product: "Macaron Pistache", rating: 5 },
  ],
};
